# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeffery's Note
email: chiachun2491@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  做完一些作業或題目後，很閒的時候筆記起來。
baseurl: "/NTUST_Exercise" # the subpath of your site, e.g. /blog
url: "https://chiachun2491.github.io" # the base hostname & protocol for your site
github_username:  chiachun2491

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics:
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
